[tool.poetry]
name = "secas-blueprint"
version = "1.0.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }]

[tool.poetry.dependencies]
python = "^3.9"
geopandas = "^0.12.2"
affine = "^2.4.0"
aiofiles = "^23.1.0"
fastapi = "^0.95.1"
Jinja2 = "^3.1.2"
numpy = "^1.24.3"
pandas = "^1.5.3"
Pillow = "^9.4.0"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
rasterio = "^1.3.6"
sentry-sdk = "^1.18.0"
uvicorn = "^0.22.0"
weasyprint = "^59.0"
pyarrow = "^11.0.0"
arq = "^0.25.0"
isort = "^5.10.1"
shapely = "^2.0.1"
pymgl = {path = "../pymgl/dist/pymgl-0.3.1+10.gd13d070-cp310-cp310-macosx_12_0_arm64.whl"} # wheel is built locally for Arm64
pyogrio = "^0.6.0"
openpyxl = "^3.1.2"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
Cython = "^0.29.30"
watchgod = "^0.8.2"
progress = "^1.6"
httpx = {extras = ["http2"], version = "^0.24.0"}
watchfiles = "^0.19.0"
ruff = "^0.0.260"

[tool.isort]
profile = "black"

[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "numpy", "Cython"]
build-backend = "poetry.core.masonry.api"
