[tool.poetry]
name = "secas-blueprint"
version = "1.0.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }]

[tool.poetry.dependencies]
python = "3.10"
geopandas = "^0.14.0"
affine = "^2.4.0"
aiofiles = "^23.2.1"
fastapi = "^0.95.2"
Jinja2 = "^3.1.2"
numpy = "^1.26.0"
pandas = "^2.1.1"
Pillow = "^10.0.1"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
rasterio = "^1.3.8"
sentry-sdk = "^1.31.0"
uvicorn = "^0.23.2"
weasyprint = "^60.0"
pyarrow = "^13.0.0"
arq = "^0.25.0"
shapely = "^2.0.1"
# FIXME:
# pymgl = { path = "../pymgl/dist/pymgl-0.3.1+10.gd13d070-cp310-cp310-macosx_12_0_arm64.whl" } # wheel is built locally for Arm64
pyogrio = "^0.7.2"
openpyxl = "^3.1.2"
gunicorn = "^21.2.0"

[tool.poetry.dev-dependencies]
Cython = "^3.0.2"
watchgod = "^0.8.2"
progress = "^1.6"
httpx = { extras = ["http2"], version = "^0.25.0" }
watchfiles = "^0.19.0"
ruff = "^0.1.2"

[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "numpy", "Cython"]
build-backend = "poetry.core.masonry.api"
