[project]
name = "secas-blueprint"
version = "1.2.0"
description = "SECAS Southeast Conservation Blueprint Explorer"
readme = "README.md"
authors = [{ name = "Brendan C. Ward", email = "bcward@astutespruce.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.12"
dependencies = [
    "affine",
    "aiofiles",
    "arq",
    "fastapi",
    "geopandas",
    "gunicorn",
    "Jinja2",
    "numba>=0.61.2",
    "numpy",
    "openpyxl>=3.1.5",
    "pandas",
    "Pillow",
    "progress",
    "pyarrow",
    "pymgl",
    "pyogrio",
    "python-calamine",
    "python-dotenv",
    "python-multipart",
    "rasterio",
    "sentry-sdk",
    "shapely",
    "uvicorn",
    "weasyprint",
]

[project.optional-dependencies]
dev = [
    "httpx[http2]",
    "ruff",
    "setuptools",
    "watchgod",
    "watchfiles",
    "typer>=0.27.2",
]
tests = ["httpx>=0.28.1", "pixelmatch>=0.4.0", "pytest>=9.1.1"]

[project.scripts]
create-report = "commands.report:app"
filter-blueprint = "commands.filter:app"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = ["analysis", "api", "commands"]
namespace = true

[tool.ruff]
line-length = 120
