[tool.poetry]
name = "secas-blueprint"
version = "1.1.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"
packages = [{ include = "analysis" }]

[tool.poetry.dependencies]
python = "^3.10"
geopandas = "^0.14.3"
affine = "^2.4.0"
aiofiles = "^23.2.1"
fastapi = "^0.110.0"
Jinja2 = "^3.1.3"
numpy = "^1.26.4"
pandas = "^2.2.1"
Pillow = "^10.2.0"
python-dotenv = "^1.0.1"
python-multipart = "^0.0.9"
rasterio = "^1.3.9"
sentry-sdk = "^1.40.6"
uvicorn = "^0.27.1"
weasyprint = "^61.1"
pyarrow = "^15.0.0"
arq = "^0.25.0"
shapely = "^2.0.3"
# FIXME:
# pymgl = { path = "../pymgl/dist/pymgl-0.3.1+10.gd13d070-cp310-cp310-macosx_12_0_arm64.whl" } # wheel is built locally for Arm64
pyogrio = "^0.7.2"
openpyxl = "^3.1.2"
gunicorn = "^21.2.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.0"
cython = "^3.0.8"
httpx = {extras = ["http2"], version = "^0.27.0"}
watchgod = "^0.8.2"
progress = "^1.6"
watchfiles = "^0.21.0"

[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "numpy", "Cython"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = ['.scratch']