version: '3.6'
services:
  redis:
    image: 'redis:alpine'
    logging:
      driver: journald

  mbtileserver:
    image: consbio/mbtileserver:latest
    restart: always
    volumes:
      - /tiles:/tilesets
    logging:
      driver: journald

  renderer:
    image: consbio/mbgl-renderer:latest
    restart: always
    volumes:
      - /tiles:/app/tiles
    logging:
      driver: journald

  api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    command:
      [
        '/usr/local/bin/gunicorn',
        '-k',
        'uvicorn.workers.UvicornWorker',
        '--name',
        'uvicorn',
        '-b',
        ':5000',
        'api.api:app',
      ]
    volumes:
      - user_upload:/tmp/sa-reports
      - /data:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    ports:
      - '5000:5000'

  worker:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    depends_on:
      - redis
      - renderer
    env_file:
      - .env
    command: ['/usr/local/bin/arq', 'api.worker.WorkerSettings']
    volumes:
      - user_upload:/tmp/sa-reports
      - /data:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators

  caddy:
    image: caddy/caddy:2.1.1-alpine
    depends_on:
      - mbtileserver
      - api
      - worker
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - /var/www:/var/www
    logging:
      driver: journald

volumes:
  caddy_certs:
  user_upload:
