version: '3.6'
services:
  se-api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    external_links:
      - redis
    env_file:
      - .env
    command:
      [
        '/usr/local/bin/gunicorn',
        '-k',
        'uvicorn.workers.UvicornWorker',
        '--name',
        'uvicorn',
        '--workers',
        '1', # TODO: make this higher on production
        '-b',
        ':5000',
        'api.api:app',
      ]
    volumes:
      - user_upload:/tmp/se-reports
      - /data/se:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    logging:
      driver: journald
    networks:
      - shared

  se-worker:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    external_links:
      - redis
      - renderer
    env_file:
      - .env
    command: ['/usr/local/bin/arq', 'api.worker.WorkerSettings']
    volumes:
      - user_upload:/tmp/se-reports
      - /data/se:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    logging:
      driver: journald
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared

volumes:
  user_upload:
